ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    # Coordinate frames
    map_frame: map
    odom_frame: odom            # The name of the fixed frame in RViz
    base_link_frame: base_link   # Must match your robot's root link
    world_frame: odom           # Since we are not doing global (GPS/Map) navigation yet

    # Odom0: Wheel Encoders from Gazebo
    odom0: /odom
    # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    odom0_config: [false,  false,  false,  # Position X, Y
                   false, false, false,
                   true,  false, false, # Fuse X velocity, but NOT Y velocity
                   false, false, true,  # Fuse Yaw velocity
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10

    # Imu0: IMU from Gazebo
    imu0: /imu
    # Fuse orientation (yaw) and angular velocity
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false,  false, false]

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 10